description: >
  Docker's official Node image:
  http://hub.docker.com/_/node
parameters:
  resource-class:
    type: enum
    default: small
    enum: [small, medium, medium+, large, xlarge]

  tag:
    type: string
    default: latest

resource_class: <<parameters.resource-class>>

docker:
  - image: node:<<parameters.tag>>
